name = "Gruppe Adler Compat"
prefix = "grad_compat"
author = "Gruppe Adler"
files = [
    "mod.cpp",
    "Adler.paa",
    "LICENSE",
    "README.md"
]
include = [
    "./include"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip gruppe_adler_compat_{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
